import type { Metadata } from 'next'
import './globals.css'
import { eiko, inter } from '@/styles/font'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${eiko.variable}`}>{children}</body>
    </html>
  )
}
